//
//  SlideKitAtelierApp.swift
//
//  This file is automatically generated by SlideGen
//

import SwiftUI
import SlideKit

@main
struct SlideKitAtelierApp: App {
    private static let configuration = SlideConfiguration()

    var presentationContentView: some View {
        SlideRouterView(slideIndexController: Self.configuration.slideIndexController)
    }

    var body: some Scene {
        // メインのプレゼンテーションウィンドウ
        WindowGroup {
            #if os(iOS)
            PresentationView(slideSize: Self.configuration.size) {
                presentationContentView
            }
            .gesture(
                DragGesture(minimumDistance: 50)
                    .onEnded { value in
                        if value.translation.width < 0 {
                            // 左スワイプ: 次へ
                            Self.configuration.slideIndexController.forward()
                        } else if value.translation.width > 0 {
                            // 右スワイプ: 前へ
                            Self.configuration.slideIndexController.back()
                        }
                    }
            )
            #else
            PresentationView(slideSize: Self.configuration.size) {
                presentationContentView
            }
            #endif
        }
        #if os(macOS)
        .setupAsPresentationWindow(Self.configuration.slideIndexController) {
            NSWorkspace.shared.open(URL(string: "SlideKitAtelier://editor")!)
        }
        .addPDFExportCommands(
            for: presentationContentView,
            with: Self.configuration.slideIndexController,
            size: Self.configuration.size
        )
        #endif

        #if os(macOS)
        // 発表者用画面（macOSのみ）
        WindowGroup {
            macOSPresenterView(
                slideSize: Self.configuration.size,
                slideIndexController: Self.configuration.slideIndexController
            ) {
                presentationContentView
            }
        }
        .setupAsPresenterWindow()
        #endif
    }
}

// iOS用の簡易発表者ビュー（オプション）
#if os(iOS)
struct iOSPresenterView: View {
    let slideSize: CGSize
    @ObservedObject var slideIndexController: SlideIndexController
    let presentationContent: AnyView

    var body: some View {
        VStack {
            // 現在のスライド番号表示
            Text("スライド \(slideIndexController.currentIndex + 1)")
                .font(.headline)
                .padding()

            // プレゼンテーションコンテンツ
            presentationContent

            // ナビゲーションボタン
            HStack {
                Button(action: {
                    slideIndexController.back()
                }) {
                    Image(systemName: "chevron.left")
                        .font(.title)
                        .padding()
                }
                .disabled(slideIndexController.currentIndex == 0)

                Spacer()

                Button(action: {
                    slideIndexController.forward()
                }) {
                    Image(systemName: "chevron.right")
                        .font(.title)
                        .padding()
                }
            }
            .padding()
        }
    }
}
#endif
