//
//  SlideKitAtelierApp.swift
//
//  This file is automatically generated by SlideGen
//

import SwiftUI
import SlideKit

@main
// SlideKit で作るプレゼンアプリのエントリーポイント
struct SlideKitAtelierApp: App {

    // スライド全体の設定 を管理
    private static let configuration = SlideConfiguration()

    // スライドを順番に表示するビュー
    var presentationContentView: some View {
        // どのスライドを表示するか管理するコントローラー
        SlideRouterView(slideIndexController: Self.configuration.slideIndexController)
        // 全体の色を設定
            .background(.white)
            .foregroundColor(.black)
    }

    var body: some Scene {
        // スクリーンに映すプレゼン用ビュー
        WindowGroup {
            PresentationView(slideSize: Self.configuration.size) {
                presentationContentView
            }
        }
        // .setupAsPresentationWindow
        // → このウィンドウを プレゼン用として設定。
        // → ダブルクリックや特定操作でスライド編集画面を開くことも可能。
        .setupAsPresentationWindow(Self.configuration.slideIndexController) {
            NSWorkspace.shared.open(URL(string: "SlideKitAtelier://editor")!)
        }
        // メニューから PDF に書き出す機能
        .addPDFExportCommands(for: presentationContentView, with: Self.configuration.slideIndexController, size: Self.configuration.size)

        // 発表者用画面
        // 次のスライドのプレビュー
        // タイマーやノート
        // 現在のスライド番号などが確認できます。

        WindowGroup {
            macOSPresenterView(
                slideSize: Self.configuration.size,
                slideIndexController: Self.configuration.slideIndexController
            ) {
                presentationContentView
            }
        }
        // .setupAsPresenterWindow() でプレゼン用ウィンドウとリンク
        .setupAsPresenterWindow()
    }
}
